[package]
name = "jupyter2typst"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
vendored = ["reqwest/native-tls-vendored"]

[dependencies]
argh = "0.1.12"
base64 = "0.22.1"
image = { version = "0.25.1", default-features = false }
markdown = "1.0.0-alpha.17"
once_cell = "1.19.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde_json = "1.0.119"
sha1 = "0.10.6"
url = "2.5.2"
