[package]
name = "jupyter2typst"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
base64 = "0.22.1"
image = { version = "0.25.1", default-features = false }
markdown = "1.0.0-alpha.14"
once_cell = "1.18.0"
regex = "1.10.2"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde_json = "1.0.105"
sha1 = "0.10.5"
url = "2.4.1"
