[package]
name = "jupyter2typst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
base64 = "0.21.3"
engine = "0.0.0"
regex = "1.9.5"
serde_json = "1.0.105"
sha1 = "0.10.5"
